resources:
  jobs:
    full_pipeline:
      name: full_pipeline
      tasks:
        - task_key: Download_FIle
          spark_python_task:
            python_file: /Workspace/Users/mikeias.oliveira@al.infnet.edu.br/databricks-repo/etl/00_ingestion/00_download_file.py
          environment_key: Default
        - task_key: Bronze_Layer
          depends_on:
            - task_key: Copy_to_volume
          pipeline_task:
            pipeline_id: 6ef33d2b-1c68-4a0c-bb34-67747a1d1646
            full_refresh: true
        - task_key: Copy_to_volume
          depends_on:
            - task_key: Download_FIle
          spark_python_task:
            python_file: /Workspace/Users/mikeias.oliveira@al.infnet.edu.br/databricks-repo/etl/00_ingestion/01_cp_file.py
          environment_key: Default
        - task_key: Silver_Layer
          depends_on:
            - task_key: Bronze_Layer
          notebook_task:
            notebook_path: /Workspace/Users/mikeias.oliveira@al.infnet.edu.br/databricks-repo/etl/02_silver.ipynb
            source: WORKSPACE
        - task_key: Gold_Layer
          depends_on:
            - task_key: Silver_Layer
          notebook_task:
            notebook_path: /Workspace/Users/mikeias.oliveira@al.infnet.edu.br/databricks-repo/etl/03_gold.py
            source: WORKSPACE
      queue:
        enabled: true
      environments:
        - environment_key: Default
          spec:
            environment_version: "5"
      performance_target: PERFORMANCE_OPTIMIZED
